export const departments = [
  'All',
  'Secretariat',
  'Operation',
  'JCT',
  'Logistics',
  'Infomation',
  'Security',
  'Engineering Admin',
  'Elect Eng',
  'KKS',
  'Civil Eng',
  'MP Eng',
  'Navigation',
  'Human Resources',
  'Legal',
  'Welfare',
  'Medical',
  'Contract &  Designs',
  'Media',
  'Finance',
  'Mari Eng',
  'Plan & Development',
  'MW Eng',
  'Supplies',
  'Galle',
  'Trinco',
  'Audit',
  'MPMA',
  'Development',
  'Marketing',
];
